# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"URL": "00_downloading_pdfs.ipynb",
         "PDF_PATH": "00_downloading_pdfs.ipynb",
         "identify_links_for_pdfs": "00_downloading_pdfs.ipynb",
         "download_file": "00_downloading_pdfs.ipynb",
         "collect_multiple_files": "00_downloading_pdfs.ipynb",
         "extract_date_from_filename": "01_parsing_roll_call_votes.ipynb",
         "list_available_pdfs": "01_parsing_roll_call_votes.ipynb",
         "Pdf2Text": "01_parsing_roll_call_votes.ipynb",
         "get_ix": "01_parsing_roll_call_votes.ipynb",
         "useful_string": "01_parsing_roll_call_votes.ipynb",
         "SummaryParser": "01_parsing_roll_call_votes.ipynb",
         "VotesParser": "01_parsing_roll_call_votes.ipynb",
         "get_all_issues": "01_parsing_roll_call_votes.ipynb"}

modules = ["download.py",
           "parse.py"]

doc_url = "https://eschmidt42.github.io/eu_parliament/"

git_url = "https://github.com/eschmidt42/eu_parliament/tree/master/"

def custom_doc_links(name): return None
