# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_ix": "01_parsing_roll_call_votes.ipynb",
         "useful_string": "01_parsing_roll_call_votes.ipynb",
         "SummaryParser": "01_parsing_roll_call_votes.ipynb",
         "VotesParser": "01_parsing_roll_call_votes.ipynb",
         "get_all_issues": "01_parsing_roll_call_votes.ipynb"}

modules = ["parse.py"]

doc_url = "https://eschmidt42.github.io/eu_parliament/"

git_url = "https://github.com/eschmidt42/eu_parliament/tree/master/"

def custom_doc_links(name): return None
